openapi: 3.0.0
info:
  title: OTP API
  description: API for sending one-time passwords (OTP) via SMS to users.
  version: 1.0.0
paths:
  /auth/sent:
    post:
      summary: Sends OTP to the specified phone number.
      operationId: sendOtp
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: The phone number to send the OTP to.
                  example: "09123456789"
              required:
                - phone
      responses:
        "200":
          description: OTP sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "کد ورود به شماره موبایل وارد شده باموفقیت ارسال گردید."
        "409":
          description: User is restricted or OTP already sent recently.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "کد یکبارمصرف قبلا برای شما ارسال گردیده است.لطفا پس از 5 دقیقه مجدد تلاش کنید."
        "500":
          description: Error in sending OTP via SMS.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "خطا در ارسال کد یکبار مصرف،لطفا مجدد تلاش فرمائید."
        "400":
          description: Bad request due to invalid phone number or request format.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid phone number format."
  /auth/verify:
    post:
      summary: Verifies OTP and logs in the user.
      operationId: verifyOtp
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: The phone number associated with the OTP.
                  example: "09123456789"
                otpCode:
                  type: string
                  description: The OTP code received by the user.
                  example: "12345"
              required:
                - phone
                - otpCode
      responses:
        "200":
          description: User successfully logged in and received access and refresh tokens.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "شما با موفقیت وارد حساب کاربری خود شدید."
                  accessToken:
                    type: string
                    description: Access token for authenticated user.
                    example: "your-access-token-here"
                  refreshToken:
                    type: string
                    description: Refresh token for session management.
                    example: "your-refresh-token-here"
        "403":
          description: Invalid OTP or OTP has expired, or user account is restricted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "کد وارد شده صحیح نمی باشد و یا مدت زمان آن به پایان رسیده است."
        "404":
          description: User not found, and needs to be redirected to the registration page.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Redirect To Register Page."
        "400":
          description: Bad request due to missing or invalid phone number or OTP format.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid phone number or OTP format."
  /auth/register:
    post:
      summary: register User
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Ali Rezaei"
                email:
                  type: string
                  format: email
                  example: "ali@example.com"
                phone:
                  type: string
                  example: "09123456789"
                password:
                  type: string
                  format: password
                  example: "securepassword123"
              required:
                - name
                - email
                - phone
                - password
      responses:
        "201":
          description: ثبت‌نام با موفقیت انجام شد.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ثبت نام با موفقیت انجام شد."
                  accessToken:
                    type: string
                    example: "your-access-token"
                  refreshToken:
                    type: string
                    example: "your-refresh-token"
        "409":
          description: ایمیل یا شماره موبایل تکراری است.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "این آدرس ایمیل و یا شماره موبایل تکراری است."
        "400":
          description: اطلاعات ورودی معتبر نیستند.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "خطا در اعتبارسنجی اطلاعات ورودی"
  /auth/login:
    post:
      summary: User login with email or phone
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                  example: "09123456789"
                  description: Email or phone number
                password:
                  type: string
                  format: password
                  example: "securepassword123"
              required:
                - identifier
                - password
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "شما با موفقیت وارد حساب کاربری خودتون شدید."
                  accessToken:
                    type: string
                    example: "your-access-token"
                  refreshToken:
                    type: string
                    example: "your-refresh-token"
        "403":
          description: Forbidden - incorrect credentials or restricted account
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "نام کاربری و یا رمز عبور صحیح نمی باشد."
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "حساب کاربری پیدا نشد."
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ورودی نامعتبر است."
  /auth/logout:
    post:
      summary: Logout the authenticated user
      operationId: logoutUser
      tags:
        - Auth
      security:
        - accessToken: []
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "شما با موفقیت از حساب کاربری خود خارج شدید."
        "401":
          description: Unauthorized - token missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "دسترسی غیرمجاز."
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "خطایی در سرور رخ داده است."
  /auth/refresh:
    get:
      summary: Generate a new access token using a valid refresh token
      operationId: refreshAccessToken
      tags:
        - Auth
      security:
        - accessToken: []
      responses:
        "200":
          description: Access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "توکن دسترسی جدید ایجاد شد."
                  data:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "401":
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "دسترسی غیرمجاز."
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "خطایی در سرور رخ داده است."
  /auth/me:
    get:
      summary: Get current user profile and booking history
      tags:
        - Auth
      security:
        - accessToken: []
      responses:
        "200":
          description: دریافت اطلاعات کاربر و تاریخچه نوبت‌ها با موفقیت انجام شد.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "عملیات موفقیت‌آمیز بود."
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        description: اطلاعات کاربر
                      isPsychologistExist:
                        type: object
                        nullable: true
                        description: اطلاعات روانشناس (در صورت وجود)
                      appointmentHistory:
                        type: array
                        items:
                          type: object
                        description: لیست نوبت‌ها برای روانشناس
                      bookingHistory:
                        type: array
                        items:
                          type: object
                        description: لیست نوبت‌های کاربر
        "401":
          description: نیاز به احراز هویت دارد.
        "500":
          description: خطای سرور داخلی.
    patch:
      summary: Update current user profile
      operationId: updateProfile
      tags:
        - Auth
      security:
        - accessToken: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Ali Rezaei"
                email:
                  type: string
                  format: email
                  example: "ali@example.com"
                aboutMe:
                  type: string
                  example: "روانشناس کودک با تجربه‌ی ۵ ساله"
                avatar:
                  type: string
                  format: binary
      responses:
        "200":
          description: پروفایل شما با موفقیت بروزرسانی گردید.
        "400":
          description: اطلاعات ارسالی معتبر نیست.
        "401":
          description: نیاز به احراز هویت دارد.
        "500":
          description: خطای سرور داخلی.
